/*
 * Triple Triad (HTML5) - a card game from FFVIII
 * Copyright (C) 2014 Jeffrey Han
 *
 * Triple Triad is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Triple Triad is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Triple Triad.  If not, see <http://www.gnu.org/licenses/>.
 */

"use strict";

/**
 * Card deck.
 */
Game.deck = [
	{"id": 1, "name": "Geezard", "ranks": [1,5,4,1], "element": "NEUTRAL", "level": 1},
	{"id": 2, "name": "Funguar", "ranks": [5,3,1,1], "element": "NEUTRAL", "level": 1},
	{"id": 3, "name": "Bite Bug", "ranks": [1,5,3,3], "element": "NEUTRAL", "level": 1},
	{"id": 4, "name": "Red Bat", "ranks": [6,2,1,1], "element": "NEUTRAL", "level": 1},
	{"id": 5, "name": "Blobra", "ranks": [2,5,3,1], "element": "NEUTRAL", "level": 1},
	{"id": 6, "name": "Gayla", "ranks": [2,4,1,4], "element": "THUNDER", "level": 1},
	{"id": 7, "name": "Gesper", "ranks": [1,1,5,4], "element": "NEUTRAL", "level": 1},
	{"id": 8, "name": "Fastitocalon-F", "ranks": [3,1,5,2], "element": "EARTH", "level": 1},
	{"id": 9, "name": "Blood Soul", "ranks": [2,1,1,6], "element": "NEUTRAL", "level": 1},
	{"id": 10, "name": "Caterchipillar", "ranks": [4,3,2,4], "element": "NEUTRAL", "level": 1},
	{"id": 11, "name": "Cockatrice", "ranks": [2,6,1,2], "element": "THUNDER", "level": 1},
	{"id": 12, "name": "Grat", "ranks": [7,1,1,3], "element": "NEUTRAL", "level": 2},
	{"id": 13, "name": "Buel", "ranks": [6,3,2,2], "element": "NEUTRAL", "level": 2},
	{"id": 14, "name": "Mesmerize", "ranks": [5,4,3,3], "element": "NEUTRAL", "level": 2},
	{"id": 15, "name": "Glacial Eye", "ranks": [6,3,1,4], "element": "ICE", "level": 2},
	{"id": 16, "name": "Belhelmel", "ranks": [3,3,4,5], "element": "NEUTRAL", "level": 2},
	{"id": 17, "name": "Thrustaevis", "ranks": [5,5,3,2], "element": "WIND", "level": 2},
	{"id": 18, "name": "Anacondaur", "ranks": [5,5,1,3], "element": "POISON", "level": 2},
	{"id": 19, "name": "Creeps", "ranks": [5,2,2,5], "element": "THUNDER", "level": 2},
	{"id": 20, "name": "Grendel", "ranks": [4,2,4,5], "element": "THUNDER", "level": 2},
	{"id": 21, "name": "Jelleye", "ranks": [3,7,2,1], "element": "NEUTRAL", "level": 2},
	{"id": 22, "name": "Grand Mantis", "ranks": [5,3,2,5], "element": "NEUTRAL", "level": 2},
	{"id": 23, "name": "Forbidden", "ranks": [6,2,6,3], "element": "NEUTRAL", "level": 3},
	{"id": 24, "name": "Armadodo", "ranks": [6,6,3,1], "element": "EARTH", "level": 3},
	{"id": 25, "name": "Tri-Face", "ranks": [3,5,5,5], "element": "POISON", "level": 3},
	{"id": 26, "name": "Fastitocalon", "ranks": [7,3,5,1], "element": "EARTH", "level": 3},
	{"id": 27, "name": "Snow Lion", "ranks": [7,3,1,5], "element": "ICE", "level": 3},
	{"id": 28, "name": "Ochu", "ranks": [5,3,6,3], "element": "NEUTRAL", "level": 3},
	{"id": 29, "name": "SAM08G", "ranks": [5,4,6,2], "element": "FIRE", "level": 3},
	{"id": 30, "name": "Death Claw", "ranks": [4,2,4,7], "element": "FIRE", "level": 3},
	{"id": 31, "name": "Cactuar", "ranks": [6,3,2,6], "element": "NEUTRAL", "level": 3},
	{"id": 32, "name": "Tonberry", "ranks": [3,4,6,4], "element": "NEUTRAL", "level": 3},
	{"id": 33, "name": "Abyss Worm", "ranks": [7,5,2,3], "element": "EARTH", "level": 3},
	{"id": 34, "name": "Turtapod", "ranks": [2,7,3,6], "element": "NEUTRAL", "level": 4},
	{"id": 35, "name": "Vysage", "ranks": [6,5,5,4], "element": "NEUTRAL", "level": 4},
	{"id": 36, "name": "T-Rexaur", "ranks": [4,7,6,2], "element": "NEUTRAL", "level": 4},
	{"id": 37, "name": "Bomb", "ranks": [2,3,7,6], "element": "FIRE", "level": 4},
	{"id": 38, "name": "Blitz", "ranks": [1,7,6,4], "element": "THUNDER", "level": 4},
	{"id": 39, "name": "Wendigo", "ranks": [7,6,3,1], "element": "NEUTRAL", "level": 4},
	{"id": 40, "name": "Torama", "ranks": [7,4,4,4], "element": "NEUTRAL", "level": 4},
	{"id": 41, "name": "Imp", "ranks": [3,6,7,3], "element": "NEUTRAL", "level": 4},
	{"id": 42, "name": "Blue Dragon", "ranks": [6,3,2,7], "element": "POISON", "level": 4},
	{"id": 43, "name": "Adamantoise", "ranks": [4,6,5,5], "element": "EARTH", "level": 4},
	{"id": 44, "name": "Hexadragon", "ranks": [7,3,5,4], "element": "FIRE", "level": 4},
	{"id": 45, "name": "Iron Giant", "ranks": [6,5,5,6], "element": "NEUTRAL", "level": 5},
	{"id": 46, "name": "Behemoth", "ranks": [3,7,6,5], "element": "NEUTRAL", "level": 5},
	{"id": 47, "name": "Chimera", "ranks": [7,3,6,5], "element": "WATER", "level": 5},
	{"id": 48, "name": "PuPu", "ranks": [3,1,10,2], "element": "NEUTRAL", "level": 5},
	{"id": 49, "name": "Elastoid", "ranks": [6,7,2,6], "element": "NEUTRAL", "level": 5},
	{"id": 50, "name": "GIM47N", "ranks": [5,4,5,7], "element": "NEUTRAL", "level": 5},
	{"id": 51, "name": "Malboro", "ranks": [7,2,7,4], "element": "POISON", "level": 5},
	{"id": 52, "name": "Ruby Dragon", "ranks": [7,4,2,7], "element": "FIRE", "level": 5},
	{"id": 53, "name": "Elnoyle", "ranks": [5,6,3,7], "element": "NEUTRAL", "level": 5},
	{"id": 54, "name": "Tonberry King", "ranks": [4,4,6,7], "element": "NEUTRAL", "level": 5},
	{"id": 55, "name": "Wedge, Biggs", "ranks": [6,7,6,2], "element": "NEUTRAL", "level": 5},
	{"id": 56, "name": "Fujin Raijin", "ranks": [2,4,8,8], "element": "NEUTRAL", "level": 6},
	{"id": 57, "name": "Elvoret", "ranks": [7,4,8,3], "element": "WIND", "level": 6},
	{"id": 58, "name": "X-ATM092", "ranks": [4,3,8,7], "element": "NEUTRAL", "level": 6},
	{"id": 59, "name": "Granaldo", "ranks": [7,5,2,8], "element": "NEUTRAL", "level": 6},
	{"id": 60, "name": "Gerogero", "ranks": [1,3,8,8], "element": "POISON", "level": 6},
	{"id": 61, "name": "Iguion", "ranks": [8,2,2,8], "element": "NEUTRAL", "level": 6},
	{"id": 62, "name": "Abadon", "ranks": [6,5,8,4], "element": "NEUTRAL", "level": 6},
	{"id": 63, "name": "Trauma", "ranks": [4,6,8,5], "element": "NEUTRAL", "level": 6},
	{"id": 64, "name": "Oilboyle", "ranks": [1,8,8,4], "element": "NEUTRAL", "level": 6},
	{"id": 65, "name": "Shumi", "ranks": [6,4,5,8], "element": "NEUTRAL", "level": 6},
	{"id": 66, "name": "Krysta", "ranks": [7,1,5,8], "element": "NEUTRAL", "level": 6},
	{"id": 67, "name": "Propagator", "ranks": [8,8,4,4], "element": "NEUTRAL", "level": 7},
	{"id": 68, "name": "Jumbo Cactuar", "ranks": [8,4,8,4], "element": "NEUTRAL", "level": 7},
	{"id": 69, "name": "Tri-Point", "ranks": [8,8,5,2], "element": "THUNDER", "level": 7},
	{"id": 70, "name": "Gargantua", "ranks": [5,8,6,6], "element": "NEUTRAL", "level": 7},
	{"id": 71, "name": "Mobile Type 8", "ranks": [8,3,6,7], "element": "NEUTRAL", "level": 7},
	{"id": 72, "name": "Sphinxara", "ranks": [8,8,3,5], "element": "NEUTRAL", "level": 7},
	{"id": 73, "name": "Tiamat", "ranks": [8,4,8,5], "element": "NEUTRAL", "level": 7},
	{"id": 74, "name": "BGH251F2", "ranks": [5,5,7,8], "element": "NEUTRAL", "level": 7},
	{"id": 75, "name": "Red Giant", "ranks": [6,7,8,4], "element": "NEUTRAL", "level": 7},
	{"id": 76, "name": "Catoblepas", "ranks": [1,7,8,7], "element": "NEUTRAL", "level": 7},
	{"id": 77, "name": "Ultima Weapon", "ranks": [7,8,7,2], "element": "NEUTRAL", "level": 7},
	{"id": 78, "name": "Chubby Chocobo", "ranks": [4,9,4,8], "element": "NEUTRAL", "level": 8},
	{"id": 79, "name": "Angelo", "ranks": [9,3,6,7], "element": "NEUTRAL", "level": 8},
	{"id": 80, "name": "Gilgamesh", "ranks": [3,6,7,9], "element": "NEUTRAL", "level": 8},
	{"id": 81, "name": "MiniMog", "ranks": [9,2,3,9], "element": "NEUTRAL", "level": 8},
	{"id": 82, "name": "Chicobo", "ranks": [9,4,4,8], "element": "NEUTRAL", "level": 8},
	{"id": 83, "name": "Quezacotl", "ranks": [2,4,9,9], "element": "THUNDER", "level": 8},
	{"id": 84, "name": "Shiva", "ranks": [6,9,7,4], "element": "ICE", "level": 8},
	{"id": 85, "name": "Ifrit", "ranks": [9,8,6,2], "element": "FIRE", "level": 8},
	{"id": 86, "name": "Siren", "ranks": [8,2,9,6], "element": "NEUTRAL", "level": 8},
	{"id": 87, "name": "Sacred", "ranks": [5,9,1,9], "element": "EARTH", "level": 8},
	{"id": 88, "name": "Minotaur", "ranks": [9,9,5,2], "element": "EARTH", "level": 8},
	{"id": 89, "name": "Carbuncle", "ranks": [8,4,4,10], "element": "NEUTRAL", "level": 9},
	{"id": 90, "name": "Diablos", "ranks": [5,3,10,8], "element": "NEUTRAL", "level": 9},
	{"id": 91, "name": "Leviathan", "ranks": [7,7,10,1], "element": "WATER", "level": 9},
	{"id": 92, "name": "Odin", "ranks": [8,5,10,3], "element": "NEUTRAL", "level": 9},
	{"id": 93, "name": "Pandemona", "ranks": [10,7,1,7], "element": "WIND", "level": 9},
	{"id": 94, "name": "Cerberus", "ranks": [7,10,4,6], "element": "NEUTRAL", "level": 9},
	{"id": 95, "name": "Alexander", "ranks": [9,2,10,4], "element": "HOLY", "level": 9},
	{"id": 96, "name": "Phoenix", "ranks": [7,10,2,7], "element": "FIRE", "level": 9},
	{"id": 97, "name": "Bahamut", "ranks": [10,6,8,2], "element": "NEUTRAL", "level": 9},
	{"id": 98, "name": "Doomtrain", "ranks": [3,10,1,10], "element": "POISON", "level": 9},
	{"id": 99, "name": "Eden", "ranks": [4,10,4,9], "element": "NEUTRAL", "level": 9},
	{"id": 100, "name": "Ward", "ranks": [10,8,7,2], "element": "NEUTRAL", "level": 10},
	{"id": 101, "name": "Kiros", "ranks": [6,10,7,6], "element": "NEUTRAL", "level": 10},
	{"id": 102, "name": "Laguna", "ranks": [5,9,10,3], "element": "NEUTRAL", "level": 10},
	{"id": 103, "name": "Selphie", "ranks": [10,4,8,6], "element": "NEUTRAL", "level": 10},
	{"id": 104, "name": "Quistis", "ranks": [9,2,6,10], "element": "NEUTRAL", "level": 10},
	{"id": 105, "name": "Irvine", "ranks": [2,10,6,9], "element": "NEUTRAL", "level": 10},
	{"id": 106, "name": "Zell", "ranks": [8,6,5,10], "element": "NEUTRAL", "level": 10},
	{"id": 107, "name": "Rinoa", "ranks": [4,10,10,2], "element": "NEUTRAL", "level": 10},
	{"id": 108, "name": "Edea", "ranks": [10,3,10,3], "element": "NEUTRAL", "level": 10},
	{"id": 109, "name": "Seifer", "ranks": [6,4,9,10], "element": "NEUTRAL", "level": 10},
	{"id": 110, "name": "Squall", "ranks": [10,9,4,6], "element": "NEUTRAL", "level": 10}
];